//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorm_Quiz2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugDetail
    {
        public int drugId { get; set; }
        public string drugName { get; set; }
        public string drugDescription { get; set; }
        public string drugDosage { get; set; }
        public string drugMethod { get; set; }
        public int drugUnitsPerDay { get; set; }
        public System.DateTime drugStartDate { get; set; }
        public System.DateTime drugEndDate { get; set; }
        public string PId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
