//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorm_Quiz2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities4 : DbContext
    {
        public Entities4()
            : base("name=Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DrugDetail> DrugDetails { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<WardDetail> WardDetails { get; set; }
    }
}
