//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorm_Quiz2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardDetail
    {
        public string WardId { get; set; }
        public string WardName { get; set; }
        public string PId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
